---
title: "lda_project"
author: "Mafe"
date: "25/5/2022"
output: html_document
---

```{r, include=FALSE}

library(MASS)
library(dplyr)
library(magrittr)
library(caret)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

## LDA


```{r}
data1 = read.csv('C:/Users/Mafe/Documents/AED/proyectoAED/proyectoAED/data_bonita_ph.csv',sep = ";")
```

Iniciamos hacer el LDA 
```{r}
set.seed(200)
#Aquí estamos dividiendo el conjuntO de datos en 70% training
training.samples <- data1$NivelDePH %>% createDataPartition(p=0.7, list=FALSE)
train.data <- data1[training.samples, ]
#Aquí depositamos el 30% restante para probar
test.data <- data1[-training.samples, ]

preproc.param <- train.data %>% preProcess(method=c("center","scale"))
train.transformed.data <- preproc.param %>% predict(train.data)
test.transformed.data <- preproc.param %>% predict(test.data)
```

```{r}
#Estimación del modelo mediante LDA
model_data<-lda(Departamento~NivelDePH, data=train.transformed.data)
#Predicciones del modelo
predictions_data <- model_data %>%predict(test.transformed.data)
#Gaficamos las respuestas del modelo
model_data
```
```{r}
plot(model_data, main= "Gráfico discriminantes lineales")
```

```{r}
#Estimación del modelo mediante LDA
model_data2<-lda(Departamento~pH.agua.suelo.2.5.1.0, data=train.transformed.data)
#Predicciones del modelo
predictions_data <- model_data2 %>%predict(test.transformed.data)
#Gaficamos las respuestas del modelo
model_data2

```
```{r}
a= data1$Departamento
training1 = data1[7]
model_LDA1 = lda(a~., training1)
model_LDA1
```

